server:
  port: 8080


spring:
  application:
    name:

# DataSource Setting
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/pltoo
    username: root
    password: 12345

  # Thymeleaf Cache Setting
  thymeleaf:
      cache: false
      suffix: .html
      prefix: classpath:/templates/

  # JPA Setting
  jpa:
    open-in-view: false
    show-sql: true
    hibernate:
      ddl-auto: update
